### ISSUE TITLE
As a user, I want an easier way to navigate to the github pages documentation

### ISSUE THREAD

**Issue by aaraney** [hydroshare/hsclient#17]
Currently, the only way to get to the [`gh-pages`](https://hydroshare.github.io/hsclient/) documentation is through clicking the `github-pages` link under environments in the code tab of the repo. I would like a link in the about section for easier access. 

Thoughts @sblack-usu?

**Comment by sblack-usu** [comment]
That would make it much easier to find the documentation.  If you've got time, you're welcome to submit a PR to get it updated.

**Comment by aaraney** [comment]
Im happy to open one to add it to the readme, I won't be able to add it to about section I think that's a repository setting I don't have access to.

**Comment by sblack-usu** [comment]
Right, sorry, that makes sense.  I'll go ahead and update it in the settings.

**Comment by aaraney** [comment]
No worries, thanks for doing that! Have a nice weekend.
