### ISSUE TITLE
ResourcePreview authors field does not default to empty list if authors not present

### ISSUE THREAD

**Issue by aaraney** [hydroshare/hsclient#23]
By my reading of the [source](https://github.com/hydroshare/hsclient/blob/2242fccf4ffda9a1b0bb408715b38170ee31ea14/hsclient/json_models.py#L38), I assume when a HS resource does not include an author, the desired outcome is an empty list. As it stands, this is not the case. If a HS resource does not have an author, `None` is returned in the model. See pydantic [validator](https://pydantic-docs.helpmanual.io/usage/validators/#validate-always) docs for reference.

**Comment by aaraney** [comment]
@sblack-usu, if you can verify my assumption, im happy to open a PR to resolve this.

**Comment by sblack-usu** [comment]
Is this an issue you've come across or is it something you noticed when reading the code?  I see what you're saying and updating the default from None to an empty list makes sense to me.  I do not recall why that validator is there... I don't think a resource should have zero authors.  

I'd be happy to take a PR to fix this.  The search functionality needs to be revisited at a later time.  This implementation wraps a very old API endpoint that needs to be modernized.
