### ISSUE TITLE
hsclient depends on specific version of hsmodels, is this intentional? 

### ISSUE THREAD

**Issue by aaraney** [hydroshare/hsclient#30]
`hsclient` depends on [`hsmodels==0.2.5`](https://github.com/hydroshare/hsclient/blob/9b681ef8c2178d99439170da10e93680e9b484a6/setup.py#L12), is this intentional? or should this be a `>=` constraint?

**Comment by sblack-usu** [comment]
I've updated it to a >= constraint now.
