### ISSUE TITLE
get userinfo by username error against hydroshare 1.50

### ISSUE THREAD

**Issue by zhiyuli** [hydroshare/hsclient#33]
@sblack-usu 

We are testing the "get userinfo by username" feature against hydroshare 1.50. We are seeing the following error on most users we   intend to check on.

![image](https://user-images.githubusercontent.com/10070599/142452017-da51005b-b995-4c9f-a50a-cbd585edcd1d.png)

**Comment by aaraney** [comment]
@sblack-usu it looks like a problem with the pydantic validator added to the `User` model in a21659bcf1c34f57fcda13a073cc377a0b5555ce. I'll open a PR to fix this.

**Comment by aaraney** [comment]
@zhiyuli, #34 should resolve this issue. I just verified it locally. @zhiyuli you can install my hotfix branch using: `pip install git+https://github.com/aaraney/hsclient.git@fix_33`.

**Comment by sblack-usu** [comment]
I'll get a patch release out today.  Thanks @aaraney.

**Comment by zhiyuli** [comment]
@aaraney Thanks for the quick fix. We just tested it and ran into a new error for the following users
christinabandaragoda
jbeaulieu
paulfloury
linnea
rstrauch
gantian
stella
jpally
zzoo
kortney09
branhoff
scicommsadie
sohsaid
tonycastronova
gokulanand
github_zyli2004
uillinois_zhiyul
zhiyuli
uillinois_zhiyul@illinois.edu
laurencejnote
nicoleta
bechir
marti_nogues
ashlingj
maram
lgraup
motasem
kevinc0223
claracogswell
kristina_roller


![image](https://user-images.githubusercontent.com/10070599/142462900-944ec071-ccca-4ab9-854e-9b6cc8f98206.png)

**Comment by aaraney** [comment]
@zhiyuli, having just tested a few of these users using the [`hsapi` swagger docs](https://www.hydroshare.org/hsapi/), this appears to be an issue with the `/hsapi/userDetails` endpoint not `hsclient` directly. For that reason, I will open an issue on the HydroShare project, ref it here, and maybe we can move conversation there just for continuity.
